# Generated by Django 4.2.2 on 2023-07-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('correct_count', models.PositiveIntegerField()),
                ('damaged_count', models.PositiveIntegerField()),
                ('resource_type', models.CharField(choices=[('ELECTRICAL', 'Electrical'), ('PLUMBING', 'Plumbing'), ('CARPENTRY', 'Carpentry'), ('SANITATION', 'Sanitation'), ('OTHERS', 'Others')], default='OTHERS', max_length=15)),
                ('resource_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
