# Generated by Django 4.2.2 on 2023-07-10 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('floor_number', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('occupancy_status', models.CharField(choices=[('OCCUPIED', 'Occupied'), ('VACANT', 'Vacant')], default='VACANT', max_length=10)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student')),
            ],
        ),
    ]
