# Generated by Django 4.2.2 on 2023-07-11 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('room', '0003_alter_room_options_alter_room_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
    ]
