# Generated by Django 4.2.2 on 2023-07-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_alter_mess_contact_number_alter_mess_cost_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess',
            name='cost_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='mess',
            name='rebate_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
