# Generated by Django 4.2.2 on 2023-07-12 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rebate',
            fields=[
                ('total_contiguous_leaves', models.PositiveIntegerField(default=0)),
                ('rebate_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rebate_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.leave')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
