# Generated by Django 4.2.2 on 2023-08-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rebate'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='rebate_associated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
